### PR TITLE
Use SystemTime rather than DateTime directly

### PR DESCRIPTION
**Pull request by georgehemmings**
Hey @jezzsantos, it can be useful to be able to control time in testing and staging. As SS already has `SystemTime` I've replaced direct use DateTime.

### CODE REVIEW

**Comment by jezzsantos** [comment]
Hi George, this is very interesting. Thanks.
Kind of being looking for something like where we can control actual time in testing for a long time.

So, what's the idea?
If you use `SystemTime` in both the tests and the code, then somehow you can manipulate the underlying clock in a test, to fastforward/rewind the time that the code thinks it is?

**Comment by georgehemmings** [comment]
That's right, in tests you can just set the [resolver](https://github.com/ServiceStack/ServiceStack.Text/blob/master/tests/ServiceStack.Text.Tests/SystemTimeTests.cs) in the test.

**Comment by jezzsantos** [comment]
Great stuff.

We should probably either then: agree to replace all use of `DateTime` everywhere in the code/tests with `SystemTime`, or continue using other time testing patterns. (Consistency is the most important thing here).

**Comment by jezzsantos** [comment]
BTW: don't worry about the build failing, I am getting that resolved with AppVeyor. As soon as that is resolved, I'll sort out the PR's that are queuing up!

**Pull request merged**
