### PR TITLE
New OrmLite Subscription Data Store

### PR DESCRIPTION
**Pull request by mythz**
This PR adds OrmLite back-end support for storing subscriptions in any of [OrmLite's supported databases](https://github.com/ServiceStack/ServiceStack.OrmLite#download).

I've added an optional `InitSchema()` extension method which can be called to create the data store schemas for the data stores that need it. If the `ISubscriptionStore` implements `IRequiresSchema` it will call it, otherwise it will ignore it so it's always safe to call for any data store.

To make use of `OrmLiteSubscriptionStore` you first need to install the [OrmLite NuGet package of the RDBMS](https://github.com/ServiceStack/ServiceStack.OrmLite#download) you wish to use then register the Dialect Provider and connection string you wish to use, e.g:

```csharp
container.Register<IDbConnectionFactory>(c => 
    new OrmLiteConnectionFactory(connectionString, SqlServer2012Dialect.Provider));
``` 

Which is used to register the `OrmLiteSubscriptionStore`:

```csharp
container.Register<ISubscriptionStore>(c => 
    new OrmLiteSubscriptionStore(c.Resolve<IDbConnectionFactory>()));

//Create WebhookSubscription and SubscriptionDeliveryResult tables if they don't exist
container.Resolve<ISubscriptionStore>().InitSchema();
```

### CODE REVIEW

**Comment by mythz** [comment]
Looks like the build is failing because AppVeyor doesn't like the test projects reference to [ServiceStack.OrmLite.Sqlite.Mono](https://www.nuget.org/packages/ServiceStack.OrmLite.Sqlite.Mono) which uses a native **x86** sqlite3.dll. I prefer using this version because it also works on Mono, but will change it to use the [ServiceStack.OrmLite.Sqlite.Windows](https://www.nuget.org/packages/ServiceStack.OrmLite.Sqlite.Windows) mixed-mode package to see if it helps.

**Comment by mythz** [comment]
The build is failing due to free quot Exception, you'll need to register a license key in `SERVICESTACK_LICENSE` environment variable in AppVeyor.

**Comment by jezzsantos** [comment]
I added the `SERVICESTACK_LICENSE` environment variable to all configurations the build matrix, (was actually only missing from one of the configurations of the build matrix).

Now i see it in the configuration when the builds are made. It is there, but looks  like we are still getting the error. Any ideas?

**Comment by jezzsantos** [comment]
I am just fixing the PR up right now. (sorry had to duck out for a few hours)
Should we be creating a "ServiceStack.Webhooks.OrmLite" nuget from this, from the "Webhooks.OrmLite" project do you think?

**Comment by jezzsantos** [comment]
I don't really understand why the build is failing.

I have not had much experience with using the `SERVICESTACK_LICENSE` as an environment variable, since in other SS projects we have been using the license key in code.

This is how the AppVeyor project for 'ServiceStack.Webhooks' is configured:
(I am using my personal SS license key here - obscured for security)

capture

What else do I need to do?

**Comment by mythz** [comment]
Don't know why it's not working in AppVeyor, it just needs to be available in the `SERVICESTACK_LICENSE` Environment variable in the AppHost for it to work.

You can try registering it explicitly to check whether the AppHost has Environment Variable available or not, e.g:

```csharp
var licenseKeyText = Environment.GetEnvironmentVariable("SERVICESTACK_LICENSE")?.Trim();
if (!string.IsNullOrEmpty(licenseKeyText)) {
    Licensing.RegisterLicense(licenseKeyText);
} else {
    Console.WriteLine("SERVICESTACK_LICENSE Environment Variable does not exist");
}
```

Which you want to run before `new AppHost().Init()`. The logs should show whether the Environment Variable exists or not.

**Comment by jezzsantos** [comment]
OK, well there is our evidence!.
capture

I'll ping Feodor, and ask what's up with that.

UPDATE: the discussion is here: http://help.appveyor.com/discussions/problems/6235-environment-variable-not-available-to-windows

**Comment by jezzsantos** [comment]
OK, seems like the problem is trying to secure the `SERVICESTACK_LICENSE` environment variable in the build configuration, since PR's are not allowed access to those variables.

The best we can do right now, is not encrypt that environment variable in the AppVeyor settings. (That has a security risk to it of course)

**Comment by jezzsantos** [comment]
Hey @mythz,

Circling back on this. I really want to find a durable and secure answer to protecting the `SERVICESTACK_LICENSE` key, which we need to have for our testing of this project.

As I discovered with AppVeyor (after some research with them) the real issue we face here, is that AppVeyor does not permit PR builds to use encrypted environment variables for public repos.

The reason they dont allow that is a very good one. (That in a public github repo, anyone can submit a PR with code that can read the encrypted environment variables, when the build/test is run). Long before we figure out the attack has been made they have the license key.

The build configuration is not visible to just anyone at the present moment, but it is to their code.

There does not seem to be any good workaround. Some options are:

* Don't encrypt the `SERVICESTACK_LICENSE` key in AppVeyor as an environment variable. Only remaining options are: leave it unencrypted and open to everyone to see, OR to use a license key file in source control, OR get it from somewhere else I guess?
* Don't allow PR's to be built in CI - that means people like yourself wont know if a PR they submit is good.
* Only allow PR's to come from a branch on the main repo (not from forks). Which means anyone submitting a PR has to have contributor rights to the repo! We can do that, but it makes it awkward to setup, and makes it far harder to send a PR.

I guess, I want to find a secure solution to this problem by somehow providing the `SERVICESTACK_LICENSE` key to the build without: (a) making it an environment variable in the build, and (b) such that we don't expose it to anyone submitting a PR, and (c) we don't disrupt the usual PR process that everyone is used to.

I am thinking there must be a way we can get the tests (when run in CI) to fetch the license key from somewhere that other devs cannot get to.

Any ideas? Seen any solutions like this?

**Comment by mythz** [comment]
If you can limit the number of Services for each integration test so it fits within the free quotas that would be ideal. But this would take effort manually registering Services individually.

Otherwise the easiest way is to disable PRs from running the build, the tests should be run locally before submitting a PR so that shouldn't be a problem. Also it's rare to get a big disruptive PR, so if it's useful and breaks a few tests I'll just fix it myself. You'd be lucky if your project gets so many PRs that this ever becomes a problem.

The other option is to use ServiceStack's precompiled dlls in /lib instead of NuGet packages, in which case you can just [use the test license key](http://stackoverflow.com/a/23718132/85785).

**Comment by jezzsantos** [comment]
OK, I think you are right. I could only wish for such a project that had so many PR's.

I will disable the build for PR's, and then see if I can get the # services under 10. Should be doable I think at this stage. YAGNI on whether I think we will have more operations in future.

Lets see if this thread comes up with any other options: http://help.appveyor.com/discussions/problems/6247-secure-secrets-in-public-github-repo-for-use-in-prs

**Pull request merged**
